import bcrypt from 'bcryptjs';
import { DbConnectionConfig, useFirebird } from './connection';
import { fbExec, fbGet, fbQuery, fbRun } from './firebird';
import { sqliteDb, sqliteExec, sqliteGet, sqliteQuery, sqliteRun } from './sqlite';

const FB_SCHEMA = `
CREATE TABLE organizations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  register VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  CONSTRAINT uq_users_org UNIQUE (org_id, username)
);

CREATE TABLE bm_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  unit VARCHAR(20) DEFAULT 'ш',
  initial_qty DOUBLE PRECISION DEFAULT 0,
  initial_price DOUBLE PRECISION DEFAULT 0,
  current_qty DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_bm_items_code UNIQUE (org_id, code)
);

CREATE TABLE bm_income (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  doc_no VARCHAR(50) NOT NULL,
  doc_date DATE NOT NULL,
  item_id INTEGER NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  total DOUBLE PRECISION NOT NULL,
  supplier VARCHAR(255),
  note VARCHAR(500),
  created_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bm_expense (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  doc_no VARCHAR(50) NOT NULL,
  doc_date DATE NOT NULL,
  item_id INTEGER NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  total DOUBLE PRECISION NOT NULL,
  purpose VARCHAR(255),
  note VARCHAR(500),
  created_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bm_sales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  doc_no VARCHAR(50) NOT NULL,
  doc_date DATE NOT NULL,
  item_id INTEGER NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  total DOUBLE PRECISION NOT NULL,
  customer VARCHAR(255),
  note VARCHAR(500),
  created_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bm_transfers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  doc_no VARCHAR(50) NOT NULL,
  doc_date DATE NOT NULL,
  item_id INTEGER NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  from_keeper VARCHAR(255) NOT NULL,
  to_keeper VARCHAR(255) NOT NULL,
  note VARCHAR(500),
  created_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bm_inventory (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  doc_no VARCHAR(50) NOT NULL,
  doc_date DATE NOT NULL,
  item_id INTEGER NOT NULL,
  book_qty DOUBLE PRECISION NOT NULL,
  actual_qty DOUBLE PRECISION NOT NULL,
  diff_qty DOUBLE PRECISION NOT NULL,
  note VARCHAR(500),
  created_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bm_loading (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id INTEGER NOT NULL,
  doc_no VARCHAR(50) NOT NULL,
  doc_date DATE NOT NULL,
  item_id INTEGER NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  load_type VARCHAR(10) NOT NULL CHECK (load_type IN ('load', 'unload')),
  vehicle VARCHAR(100),
  driver VARCHAR(255),
  note VARCHAR(500),
  created_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
`;

let fbInitialized = new Set<string>();

async function ensureFbSchema(config: DbConnectionConfig) {
  const key = config.label;
  if (fbInitialized.has(key)) return;

  const exists = await fbGet<{ cnt: number }>(
    config,
    `SELECT COUNT(*) as cnt FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'ORGANIZATIONS'`
  );

  if (!exists || exists.cnt === 0) {
    for (const stmt of FB_SCHEMA.split(';').map((s) => s.trim()).filter(Boolean)) {
      try {
        await fbRun(config, stmt);
      } catch {
        // table may already exist partially
      }
    }
    await seedFbData(config);
  }

  fbInitialized.add(key);
}

async function seedFbData(config: DbConnectionConfig) {
  const orgCount = await fbGet<{ c: number }>(config, 'SELECT COUNT(*) as c FROM organizations');
  if (orgCount && orgCount.c > 0) return;

  await fbRun(config, 'INSERT INTO organizations (register, name) VALUES (?, ?)', ['1234567', 'Тест байгууллага']);
  const org = await fbGet<{ id: number }>(config, 'SELECT id FROM organizations WHERE register = ?', ['1234567']);
  if (!org) return;

  const hash = bcrypt.hashSync('admin123', 10);
  await fbRun(config, 'INSERT INTO users (org_id, username, password, full_name) VALUES (?, ?, ?, ?)', [org.id, 'admin', hash, 'О.Оюунцэцэг']);

  const items = [
    ['BM001', 'Цаас A4', 'багц', 100, 8500],
    ['BM002', 'Үзэг хар', 'ш', 500, 500],
    ['BM003', 'Бохирын цаас', 'ш', 50, 12000],
    ['BM004', 'Бэх', 'ш', 30, 25000],
    ['BM005', 'Файл', 'ш', 200, 1500],
  ];
  for (const [code, name, unit, qty, price] of items) {
    await fbRun(config, 'INSERT INTO bm_items (org_id, code, name, unit, initial_qty, initial_price, current_qty) VALUES (?, ?, ?, ?, ?, ?, ?)', [org.id, code, name, unit, qty, price, qty]);
  }
}

function adaptSql(sql: string, firebird: boolean): string {
  if (!firebird) return sql;
  return sql
    .replace(/strftime\('%Y', doc_date\)/gi, 'EXTRACT(YEAR FROM doc_date)')
    .replace(/strftime\('%Y',doc_date\)/gi, 'EXTRACT(YEAR FROM doc_date)');
}

export async function dbGet<T>(config: DbConnectionConfig | undefined, sql: string, params: unknown[] = []): Promise<T | undefined> {
  const q = adaptSql(sql, useFirebird() && !!config);
  if (useFirebird() && config) {
    await ensureFbSchema(config);
    return fbGet<T>(config, q, params);
  }
  return sqliteGet<T>(q, params);
}

export async function dbAll<T>(config: DbConnectionConfig | undefined, sql: string, params: unknown[] = []): Promise<T[]> {
  const q = adaptSql(sql, useFirebird() && !!config);
  if (useFirebird() && config) {
    await ensureFbSchema(config);
    return fbQuery<T>(config, q, params);
  }
  return sqliteQuery<T>(q, params);
}

export async function dbRun(config: DbConnectionConfig | undefined, sql: string, params: unknown[] = []): Promise<void> {
  const q = adaptSql(sql, useFirebird() && !!config);
  if (useFirebird() && config) {
    await ensureFbSchema(config);
    await fbRun(config, q, params);
    return;
  }
  sqliteRun(q, params);
}

export async function updateItemQty(config: DbConnectionConfig | undefined, itemId: number) {
  const item = await dbGet<{ initial_qty: number }>(config, 'SELECT initial_qty FROM bm_items WHERE id = ?', [itemId]);
  if (!item) return;

  const income = (await dbGet<{ s: number }>(config, 'SELECT COALESCE(SUM(qty),0) as s FROM bm_income WHERE item_id = ?', [itemId]))?.s || 0;
  const sales = (await dbGet<{ s: number }>(config, 'SELECT COALESCE(SUM(qty),0) as s FROM bm_sales WHERE item_id = ?', [itemId]))?.s || 0;
  const expense = (await dbGet<{ s: number }>(config, 'SELECT COALESCE(SUM(qty),0) as s FROM bm_expense WHERE item_id = ?', [itemId]))?.s || 0;
  const loads = (await dbGet<{ s: number }>(config, "SELECT COALESCE(SUM(qty),0) as s FROM bm_loading WHERE item_id = ? AND load_type='load'", [itemId]))?.s || 0;
  const unloads = (await dbGet<{ s: number }>(config, "SELECT COALESCE(SUM(qty),0) as s FROM bm_loading WHERE item_id = ? AND load_type='unload'", [itemId]))?.s || 0;

  const currentQty = item.initial_qty + income + loads - sales - expense - unloads;
  await dbRun(config, 'UPDATE bm_items SET current_qty = ? WHERE id = ?', [currentQty, itemId]);
}

export async function nextDocNo(config: DbConnectionConfig | undefined, prefix: string, orgId: number) {
  const year = new Date().getFullYear();
  const tables: Record<string, string> = {
    ORL: 'bm_income', ZAR: 'bm_expense', BOR: 'bm_sales',
    SHL: 'bm_transfers', TOO: 'bm_inventory', ACH: 'bm_loading',
  };
  const table = tables[prefix] || 'bm_income';
  const count = (await dbGet<{ c: number }>(config, `SELECT COUNT(*) as c FROM ${table} WHERE org_id = ?`, [orgId]))?.c || 0;
  return `${prefix}-${year}-${String(count + 1).padStart(4, '0')}`;
}

export { sqliteDb as db };
